version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/cli"
    schedule: { interval: "weekly" }
    labels: ["dependencies", "go"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "weekly" }
    labels: ["dependencies", "github-actions"]
