// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Zero Root AI

package scaffold_test

import (
	"bytes"
	"go/parser"
	"go/token"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/zeroroot-ai/sdk/taxonomy"

	"github.com/zeroroot-ai/adk/gibson/cmd/gibson/internal/scaffold"
)

// testOntology returns a deterministic Ontology value used across tests.
func testOntology() taxonomy.Ontology {
	return taxonomy.Ontology{
		Version: "1.0",
		Prefixes: map[string]string{
			"soc2":    "https://trust.aicpa.org/soc2#",
			"nist-ai": "https://airc.nist.gov/rmf#",
		},
		Hierarchies: []taxonomy.HierarchyDef{
			{NodeType: "control", Label: "soc2:CC6", SubClassOf: ""},
			{NodeType: "control", Label: "soc2:CC6.1", SubClassOf: "soc2:CC6"},
			{NodeType: "control", Label: "soc2:CC6.2", SubClassOf: "soc2:CC6"},
		},
		Equivalences: [][2]string{
			{"soc2:CC6.1", "nist-ai:GOVERN-1.1"},
		},
		IFPs: []taxonomy.IFPDef{
			{NodeType: "control", Property: "control_id"},
		},
	}
}

// TestGenerateBytes_Deterministic runs GenerateBytes twice on the same input
// and asserts the outputs are byte-for-byte identical. This is the primary
// contract for codegen stability: version-control diffs only appear on
// intentional ontology changes.
func TestGenerateBytes_Deterministic(t *testing.T) {
	ont := testOntology()

	first, err := scaffold.GenerateBytes(ont)
	require.NoError(t, err)

	second, err := scaffold.GenerateBytes(ont)
	require.NoError(t, err)

	assert.True(t, bytes.Equal(first, second),
		"GenerateBytes must produce byte-identical output on repeated calls with the same input")
}

// TestGenerateBytes_MapKeyOrder verifies that map key ordering is stable
// across Go's random map iteration by using a prefix map with many keys.
func TestGenerateBytes_MapKeyOrder(t *testing.T) {
	ont := taxonomy.Ontology{
		Version: "1.0",
		Prefixes: map[string]string{
			"zebra":  "https://example.com/z#",
			"alpha":  "https://example.com/a#",
			"middle": "https://example.com/m#",
			"beta":   "https://example.com/b#",
		},
	}

	// Run many times to catch non-determinism from map iteration.
	first, err := scaffold.GenerateBytes(ont)
	require.NoError(t, err)

	for i := range 50 {
		got, err := scaffold.GenerateBytes(ont)
		require.NoError(t, err)
		assert.True(t, bytes.Equal(first, got),
			"iteration %d: output differed; map keys must be sorted", i)
	}
}

// TestGenerateBytes_ValidGoSource parses the generated bytes with go/parser
// to confirm the output is syntactically valid Go. This catches template
// bugs that produce malformed source without requiring a full go build.
func TestGenerateBytes_ValidGoSource(t *testing.T) {
	ont := testOntology()

	src, err := scaffold.GenerateBytes(ont)
	require.NoError(t, err)
	require.NotEmpty(t, src)

	fset := token.NewFileSet()
	_, parseErr := parser.ParseFile(fset, "ontology_extension.go", src, parser.AllErrors)
	require.NoError(t, parseErr, "generated source must be valid Go:\n%s", src)
}

// TestGenerateBytes_ZeroOntology verifies that an empty Ontology (no prefixes,
// hierarchies, etc.) still produces valid, compilable Go — not nil fields or
// panics.
func TestGenerateBytes_ZeroOntology(t *testing.T) {
	ont := taxonomy.Ontology{Version: "1.0"}

	src, err := scaffold.GenerateBytes(ont)
	require.NoError(t, err)

	fset := token.NewFileSet()
	_, parseErr := parser.ParseFile(fset, "ontology_extension.go", src, parser.AllErrors)
	require.NoError(t, parseErr, "zero-value ontology must produce valid Go:\n%s", src)
}

// TestGenerateBytes_ContainsExpectedPayload checks that the generated source
// contains the string literals from the input ontology, confirming the
// codegen actually wires the values rather than emitting empty stubs.
func TestGenerateBytes_ContainsExpectedPayload(t *testing.T) {
	ont := testOntology()

	src, err := scaffold.GenerateBytes(ont)
	require.NoError(t, err)

	s := string(src)

	// Prefix IRIs should appear in the output.
	assert.Contains(t, s, `"soc2"`, "prefix key 'soc2' should be in generated source")
	assert.Contains(t, s, `"https://trust.aicpa.org/soc2#"`, "prefix IRI for soc2 should appear")
	assert.Contains(t, s, `"nist-ai"`, "prefix key 'nist-ai' should appear")

	// Hierarchy entries.
	assert.Contains(t, s, `"soc2:CC6.1"`, "hierarchy label soc2:CC6.1 should appear")
	assert.Contains(t, s, `"soc2:CC6"`, "hierarchy subClassOf soc2:CC6 should appear")

	// Equivalence pair.
	assert.Contains(t, s, `"nist-ai:GOVERN-1.1"`, "equivalence IRI should appear")

	// IFP.
	assert.Contains(t, s, `"control_id"`, "IFP property should appear")

	// Package and function declarations.
	assert.Contains(t, s, "package gen", "generated file must declare package gen")
	assert.Contains(t, s, "func OntologyExtension()", "must export OntologyExtension func")
	assert.Contains(t, s, "graphrag.OntologyExtension{", "must return OntologyExtension struct literal")
}

// TestGenerateBytes_PrefixSortOrder verifies that the generated map literal
// has keys in lexicographic order, not Go runtime map order.
func TestGenerateBytes_PrefixSortOrder(t *testing.T) {
	ont := taxonomy.Ontology{
		Version: "1.0",
		Prefixes: map[string]string{
			"zzz": "https://z.example/",
			"aaa": "https://a.example/",
			"mmm": "https://m.example/",
		},
	}

	src, err := scaffold.GenerateBytes(ont)
	require.NoError(t, err)
	s := string(src)

	aPos := strings.Index(s, `"aaa"`)
	mPos := strings.Index(s, `"mmm"`)
	zPos := strings.Index(s, `"zzz"`)

	require.Greater(t, aPos, -1, "key 'aaa' must appear in output")
	require.Greater(t, mPos, -1, "key 'mmm' must appear in output")
	require.Greater(t, zPos, -1, "key 'zzz' must appear in output")

	assert.Less(t, aPos, mPos, "key 'aaa' must come before 'mmm' in sorted output")
	assert.Less(t, mPos, zPos, "key 'mmm' must come before 'zzz' in sorted output")
}
