// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Zero Root AI

// Package scaffold (ontology_codegen.go) — codegen for ontology.yaml files.
//
// Generate reads a parsed taxonomy.Ontology and emits a Go source file
// (gen/ontology_extension.go) into outDir. The generated file exports a
// single function OntologyExtension() that returns a fully populated
// graphrag.OntologyExtension struct ready for the daemon's Reasoner.
//
// Output is byte-stable across runs: map keys are sorted, slices are
// emitted in declaration order, and go/format is applied for canonical
// whitespace. A zero-value Ontology (no prefixes, hierarchies, etc.)
// emits a valid file with empty fields rather than nil slices, so the
// daemon can always call OntologyExtension() unconditionally.
package scaffold

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/zeroroot-ai/sdk/taxonomy"
)

// Generate reads ont and writes gen/ontology_extension.go under outDir.
// The directory is created if it does not exist. The generated file is
// byte-stable across runs: map keys are sorted and go/format is applied.
func Generate(ont taxonomy.Ontology, outDir string) error {
	src, err := renderOntologyExtension(ont)
	if err != nil {
		return fmt.Errorf("ontology codegen: render source: %w", err)
	}

	genDir := filepath.Join(outDir, "gen")
	if err := os.MkdirAll(genDir, 0o755); err != nil {
		return fmt.Errorf("ontology codegen: create gen dir: %w", err)
	}

	dst := filepath.Join(genDir, "ontology_extension.go")
	if err := os.WriteFile(dst, src, 0o644); err != nil {
		return fmt.Errorf("ontology codegen: write %s: %w", dst, err)
	}
	return nil
}

// GenerateBytes is the pure (filesystem-free) entry point used by tests.
// It returns the formatted Go source bytes for the generated file.
func GenerateBytes(ont taxonomy.Ontology) ([]byte, error) {
	return renderOntologyExtension(ont)
}

// renderOntologyExtension builds the source text for gen/ontology_extension.go
// and applies go/format for canonical whitespace. Byte stability is ensured by
// sorting map keys and emitting slices in the same order they appear in the
// Ontology value.
func renderOntologyExtension(ont taxonomy.Ontology) ([]byte, error) {
	var sb strings.Builder

	sb.WriteString("// Code generated by gibson component generate; DO NOT EDIT.\n\n")
	sb.WriteString("package gen\n\n")
	sb.WriteString("import (\n")
	sb.WriteString("\t\"github.com/zeroroot-ai/sdk/graphrag\"\n")
	sb.WriteString(")\n\n")

	sb.WriteString("// OntologyExtension returns the ontology registration payload parsed\n")
	sb.WriteString("// from ontology.yaml. Call this inside your component's main() and\n")
	sb.WriteString("// pass the result to the component registration function.\n")
	sb.WriteString("func OntologyExtension() graphrag.OntologyExtension {\n")
	sb.WriteString("\treturn graphrag.OntologyExtension{\n")

	// Prefixes — sort keys for byte stability.
	sb.WriteString("\t\tPrefixes: map[string]string{\n")
	prefixKeys := sortedStringKeys(ont.Prefixes)
	for _, k := range prefixKeys {
		sb.WriteString(fmt.Sprintf("\t\t\t%q: %q,\n", k, ont.Prefixes[k]))
	}
	sb.WriteString("\t\t},\n")

	// Hierarchies — declaration order is preserved.
	sb.WriteString("\t\tHierarchies: []graphrag.HierarchyDef{\n")
	for _, h := range ont.Hierarchies {
		sb.WriteString("\t\t\t{\n")
		sb.WriteString(fmt.Sprintf("\t\t\t\tNodeType:   %q,\n", h.NodeType))
		sb.WriteString(fmt.Sprintf("\t\t\t\tLabel:      %q,\n", h.Label))
		sb.WriteString(fmt.Sprintf("\t\t\t\tSubClassOf: %q,\n", h.SubClassOf))
		sb.WriteString("\t\t\t},\n")
	}
	sb.WriteString("\t\t},\n")

	// Equivalences — declaration order preserved; each is a [2]string literal.
	sb.WriteString("\t\tEquivalences: [][2]string{\n")
	for _, eq := range ont.Equivalences {
		sb.WriteString(fmt.Sprintf("\t\t\t{%q, %q},\n", eq[0], eq[1]))
	}
	sb.WriteString("\t\t},\n")

	// IFPs — declaration order preserved.
	sb.WriteString("\t\tIFPs: []graphrag.IFPDef{\n")
	for _, ifp := range ont.IFPs {
		sb.WriteString("\t\t\t{\n")
		sb.WriteString(fmt.Sprintf("\t\t\t\tNodeType: %q,\n", ifp.NodeType))
		sb.WriteString(fmt.Sprintf("\t\t\t\tProperty: %q,\n", ifp.Property))
		sb.WriteString("\t\t\t},\n")
	}
	sb.WriteString("\t\t},\n")

	// RawTriples — not populated from YAML; propagated if the caller sets it.
	// The generated stub leaves RawTriples as nil (zero value).
	sb.WriteString("\t}\n")
	sb.WriteString("}\n")

	src, err := format.Source([]byte(sb.String()))
	if err != nil {
		return nil, fmt.Errorf("ontology codegen: format source: %w\n\nraw source:\n%s", err, sb.String())
	}
	return src, nil
}

// sortedStringKeys returns the keys of m in lexicographic order. Returns an
// empty slice (not nil) for a nil or empty map to keep codegen output stable.
func sortedStringKeys(m map[string]string) []string {
	if len(m) == 0 {
		return []string{}
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
