// Use of this source code is governed by the Elastic License 2.0
// that can be found in the LICENSE file in the repo root.

// ConnectorService is the tenant-facing connector lifecycle (ADR-0014). A
// person enables a connector from the curated catalog and it becomes a running
// ConnectorInstance the connector-operator reconciles onto ToolHive. The person
// does not author YAML. This service is SEPARATE from ConnectorAuthService,
// which owns the OAuth grant behind an authorized connector.
//
// NOTE (Slice 4, not yet wired): the enable/disable RPCs create and delete a
// ConnectorInstance custom resource in the tenant namespace. The daemon has no
// direct Kubernetes client today (it uses the operator/enqueue pattern for
// tenant CRs). Wiring EnableConnector needs an architectural decision — give the
// daemon a scoped ConnectorInstance client, or route through the operator like
// tenant provisioning. This proto is the agreed surface; the implementation
// waits on that decision.
//
// Authorization: every RPC carries a (gibson.auth.v1.authz) annotation.

// CLIENT-ONLY COPY. Staged in the ADK from the gibson platform proto
// internal/server/daemon/api/gibson/tenant/v1/connector.proto so the OSS
// gibson CLI can generate a ConnectorService gRPC client. The (authz)
// method options are server-only and are stripped here; the wire contract
// (package gibson.tenant.v1, service and message shapes) is unchanged.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: gibson/tenant/v1/connector.proto

package tenantv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CatalogEntry is one curated connector the tenant may enable.
type CatalogEntry struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// shape is "Hosted" (a container gibson runs) or "Remote" (a vendor-hosted
	// MCP server gibson proxies).
	Shape string `protobuf:"bytes,4,opt,name=shape,proto3" json:"shape,omitempty"`
	// auth is "none", "secret", or "oauth".
	Auth          string `protobuf:"bytes,5,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatalogEntry) Reset() {
	*x = CatalogEntry{}
	mi := &file_gibson_tenant_v1_connector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogEntry) ProtoMessage() {}

func (x *CatalogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_gibson_tenant_v1_connector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogEntry.ProtoReflect.Descriptor instead.
func (*CatalogEntry) Descriptor() ([]byte, []int) {
	return file_gibson_tenant_v1_connector_proto_rawDescGZIP(), []int{0}
}

func (x *CatalogEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CatalogEntry) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CatalogEntry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CatalogEntry) GetShape() string {
	if x != nil {
		return x.Shape
	}
	return ""
}

func (x *CatalogEntry) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

type ListCatalogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCatalogRequest) Reset() {
	*x = ListCatalogRequest{}
	mi := &file_gibson_tenant_v1_connector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCatalogRequest) ProtoMessage() {}

func (x *ListCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gibson_tenant_v1_connector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCatalogRequest.ProtoReflect.Descriptor instead.
func (*ListCatalogRequest) Descriptor() ([]byte, []int) {
	return file_gibson_tenant_v1_connector_proto_rawDescGZIP(), []int{1}
}

type ListCatalogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*CatalogEntry        `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCatalogResponse) Reset() {
	*x = ListCatalogResponse{}
	mi := &file_gibson_tenant_v1_connector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCatalogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCatalogResponse) ProtoMessage() {}

func (x *ListCatalogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gibson_tenant_v1_connector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCatalogResponse.ProtoReflect.Descriptor instead.
func (*ListCatalogResponse) Descriptor() ([]byte, []int) {
	return file_gibson_tenant_v1_connector_proto_rawDescGZIP(), []int{2}
}

func (x *ListCatalogResponse) GetEntries() []*CatalogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type EnableConnectorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// catalog_id is the id of the entry to enable (for example "gitlab").
	CatalogId     string `protobuf:"bytes,1,opt,name=catalog_id,json=catalogId,proto3" json:"catalog_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableConnectorRequest) Reset() {
	*x = EnableConnectorRequest{}
	mi := &file_gibson_tenant_v1_connector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableConnectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableConnectorRequest) ProtoMessage() {}

func (x *EnableConnectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gibson_tenant_v1_connector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableConnectorRequest.ProtoReflect.Descriptor instead.
func (*EnableConnectorRequest) Descriptor() ([]byte, []int) {
	return file_gibson_tenant_v1_connector_proto_rawDescGZIP(), []int{3}
}

func (x *EnableConnectorRequest) GetCatalogId() string {
	if x != nil {
		return x.CatalogId
	}
	return ""
}

type EnableConnectorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// connector is the enabled connector's id.
	Connector string `protobuf:"bytes,1,opt,name=connector,proto3" json:"connector,omitempty"`
	// phase is the ConnectorInstance phase right after creation.
	Phase         string `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableConnectorResponse) Reset() {
	*x = EnableConnectorResponse{}
	mi := &file_gibson_tenant_v1_connector_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableConnectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableConnectorResponse) ProtoMessage() {}

func (x *EnableConnectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gibson_tenant_v1_connector_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableConnectorResponse.ProtoReflect.Descriptor instead.
func (*EnableConnectorResponse) Descriptor() ([]byte, []int) {
	return file_gibson_tenant_v1_connector_proto_rawDescGZIP(), []int{4}
}

func (x *EnableConnectorResponse) GetConnector() string {
	if x != nil {
		return x.Connector
	}
	return ""
}

func (x *EnableConnectorResponse) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

// Connector is one enabled connector and its live status.
type Connector struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Shape   string                 `protobuf:"bytes,2,opt,name=shape,proto3" json:"shape,omitempty"`
	Runtime string                 `protobuf:"bytes,3,opt,name=runtime,proto3" json:"runtime,omitempty"`
	// phase is the ConnectorInstance lifecycle phase (Pending, Provisioning,
	// AuthorizationRequired, Ready, RefreshFailing, Failed, Deprovisioning).
	Phase           string `protobuf:"bytes,4,opt,name=phase,proto3" json:"phase,omitempty"`
	DiscoveredTools int32  `protobuf:"varint,5,opt,name=discovered_tools,json=discoveredTools,proto3" json:"discovered_tools,omitempty"`
	LastError       string `protobuf:"bytes,6,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Connector) Reset() {
	*x = Connector{}
	mi := &file_gibson_tenant_v1_connector_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connector) ProtoMessage() {}

func (x *Connector) ProtoReflect() protoreflect.Message {
	mi := &file_gibson_tenant_v1_connector_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connector.ProtoReflect.Descriptor instead.
func (*Connector) Descriptor() ([]byte, []int) {
	return file_gibson_tenant_v1_connector_proto_rawDescGZIP(), []int{5}
}

func (x *Connector) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Connector) GetShape() string {
	if x != nil {
		return x.Shape
	}
	return ""
}

func (x *Connector) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *Connector) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *Connector) GetDiscoveredTools() int32 {
	if x != nil {
		return x.DiscoveredTools
	}
	return 0
}

func (x *Connector) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type ListConnectorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConnectorsRequest) Reset() {
	*x = ListConnectorsRequest{}
	mi := &file_gibson_tenant_v1_connector_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConnectorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConnectorsRequest) ProtoMessage() {}

func (x *ListConnectorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gibson_tenant_v1_connector_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConnectorsRequest.ProtoReflect.Descriptor instead.
func (*ListConnectorsRequest) Descriptor() ([]byte, []int) {
	return file_gibson_tenant_v1_connector_proto_rawDescGZIP(), []int{6}
}

type ListConnectorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connectors    []*Connector           `protobuf:"bytes,1,rep,name=connectors,proto3" json:"connectors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConnectorsResponse) Reset() {
	*x = ListConnectorsResponse{}
	mi := &file_gibson_tenant_v1_connector_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConnectorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConnectorsResponse) ProtoMessage() {}

func (x *ListConnectorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gibson_tenant_v1_connector_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConnectorsResponse.ProtoReflect.Descriptor instead.
func (*ListConnectorsResponse) Descriptor() ([]byte, []int) {
	return file_gibson_tenant_v1_connector_proto_rawDescGZIP(), []int{7}
}

func (x *ListConnectorsResponse) GetConnectors() []*Connector {
	if x != nil {
		return x.Connectors
	}
	return nil
}

type DisableConnectorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connector     string                 `protobuf:"bytes,1,opt,name=connector,proto3" json:"connector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableConnectorRequest) Reset() {
	*x = DisableConnectorRequest{}
	mi := &file_gibson_tenant_v1_connector_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableConnectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableConnectorRequest) ProtoMessage() {}

func (x *DisableConnectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gibson_tenant_v1_connector_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableConnectorRequest.ProtoReflect.Descriptor instead.
func (*DisableConnectorRequest) Descriptor() ([]byte, []int) {
	return file_gibson_tenant_v1_connector_proto_rawDescGZIP(), []int{8}
}

func (x *DisableConnectorRequest) GetConnector() string {
	if x != nil {
		return x.Connector
	}
	return ""
}

type DisableConnectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableConnectorResponse) Reset() {
	*x = DisableConnectorResponse{}
	mi := &file_gibson_tenant_v1_connector_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableConnectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableConnectorResponse) ProtoMessage() {}

func (x *DisableConnectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gibson_tenant_v1_connector_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableConnectorResponse.ProtoReflect.Descriptor instead.
func (*DisableConnectorResponse) Descriptor() ([]byte, []int) {
	return file_gibson_tenant_v1_connector_proto_rawDescGZIP(), []int{9}
}

var File_gibson_tenant_v1_connector_proto protoreflect.FileDescriptor

const file_gibson_tenant_v1_connector_proto_rawDesc = "" +
	"\n" +
	" gibson/tenant/v1/connector.proto\x12\x10gibson.tenant.v1\"\x8d\x01\n" +
	"\fCatalogEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05shape\x18\x04 \x01(\tR\x05shape\x12\x12\n" +
	"\x04auth\x18\x05 \x01(\tR\x04auth\"\x14\n" +
	"\x12ListCatalogRequest\"O\n" +
	"\x13ListCatalogResponse\x128\n" +
	"\aentries\x18\x01 \x03(\v2\x1e.gibson.tenant.v1.CatalogEntryR\aentries\"7\n" +
	"\x16EnableConnectorRequest\x12\x1d\n" +
	"\n" +
	"catalog_id\x18\x01 \x01(\tR\tcatalogId\"M\n" +
	"\x17EnableConnectorResponse\x12\x1c\n" +
	"\tconnector\x18\x01 \x01(\tR\tconnector\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\"\xab\x01\n" +
	"\tConnector\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05shape\x18\x02 \x01(\tR\x05shape\x12\x18\n" +
	"\aruntime\x18\x03 \x01(\tR\aruntime\x12\x14\n" +
	"\x05phase\x18\x04 \x01(\tR\x05phase\x12)\n" +
	"\x10discovered_tools\x18\x05 \x01(\x05R\x0fdiscoveredTools\x12\x1d\n" +
	"\n" +
	"last_error\x18\x06 \x01(\tR\tlastError\"\x17\n" +
	"\x15ListConnectorsRequest\"U\n" +
	"\x16ListConnectorsResponse\x12;\n" +
	"\n" +
	"connectors\x18\x01 \x03(\v2\x1b.gibson.tenant.v1.ConnectorR\n" +
	"connectors\"7\n" +
	"\x17DisableConnectorRequest\x12\x1c\n" +
	"\tconnector\x18\x01 \x01(\tR\tconnector\"\x1a\n" +
	"\x18DisableConnectorResponse2\xa6\x03\n" +
	"\x10ConnectorService\x12Z\n" +
	"\vListCatalog\x12$.gibson.tenant.v1.ListCatalogRequest\x1a%.gibson.tenant.v1.ListCatalogResponse\x12f\n" +
	"\x0fEnableConnector\x12(.gibson.tenant.v1.EnableConnectorRequest\x1a).gibson.tenant.v1.EnableConnectorResponse\x12c\n" +
	"\x0eListConnectors\x12'.gibson.tenant.v1.ListConnectorsRequest\x1a(.gibson.tenant.v1.ListConnectorsResponse\x12i\n" +
	"\x10DisableConnector\x12).gibson.tenant.v1.DisableConnectorRequest\x1a*.gibson.tenant.v1.DisableConnectorResponseBOZMgithub.com/zeroroot-ai/adk/gibson/internal/genproto/gibson/tenant/v1;tenantv1b\x06proto3"

var (
	file_gibson_tenant_v1_connector_proto_rawDescOnce sync.Once
	file_gibson_tenant_v1_connector_proto_rawDescData []byte
)

func file_gibson_tenant_v1_connector_proto_rawDescGZIP() []byte {
	file_gibson_tenant_v1_connector_proto_rawDescOnce.Do(func() {
		file_gibson_tenant_v1_connector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gibson_tenant_v1_connector_proto_rawDesc), len(file_gibson_tenant_v1_connector_proto_rawDesc)))
	})
	return file_gibson_tenant_v1_connector_proto_rawDescData
}

var file_gibson_tenant_v1_connector_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_gibson_tenant_v1_connector_proto_goTypes = []any{
	(*CatalogEntry)(nil),             // 0: gibson.tenant.v1.CatalogEntry
	(*ListCatalogRequest)(nil),       // 1: gibson.tenant.v1.ListCatalogRequest
	(*ListCatalogResponse)(nil),      // 2: gibson.tenant.v1.ListCatalogResponse
	(*EnableConnectorRequest)(nil),   // 3: gibson.tenant.v1.EnableConnectorRequest
	(*EnableConnectorResponse)(nil),  // 4: gibson.tenant.v1.EnableConnectorResponse
	(*Connector)(nil),                // 5: gibson.tenant.v1.Connector
	(*ListConnectorsRequest)(nil),    // 6: gibson.tenant.v1.ListConnectorsRequest
	(*ListConnectorsResponse)(nil),   // 7: gibson.tenant.v1.ListConnectorsResponse
	(*DisableConnectorRequest)(nil),  // 8: gibson.tenant.v1.DisableConnectorRequest
	(*DisableConnectorResponse)(nil), // 9: gibson.tenant.v1.DisableConnectorResponse
}
var file_gibson_tenant_v1_connector_proto_depIdxs = []int32{
	0, // 0: gibson.tenant.v1.ListCatalogResponse.entries:type_name -> gibson.tenant.v1.CatalogEntry
	5, // 1: gibson.tenant.v1.ListConnectorsResponse.connectors:type_name -> gibson.tenant.v1.Connector
	1, // 2: gibson.tenant.v1.ConnectorService.ListCatalog:input_type -> gibson.tenant.v1.ListCatalogRequest
	3, // 3: gibson.tenant.v1.ConnectorService.EnableConnector:input_type -> gibson.tenant.v1.EnableConnectorRequest
	6, // 4: gibson.tenant.v1.ConnectorService.ListConnectors:input_type -> gibson.tenant.v1.ListConnectorsRequest
	8, // 5: gibson.tenant.v1.ConnectorService.DisableConnector:input_type -> gibson.tenant.v1.DisableConnectorRequest
	2, // 6: gibson.tenant.v1.ConnectorService.ListCatalog:output_type -> gibson.tenant.v1.ListCatalogResponse
	4, // 7: gibson.tenant.v1.ConnectorService.EnableConnector:output_type -> gibson.tenant.v1.EnableConnectorResponse
	7, // 8: gibson.tenant.v1.ConnectorService.ListConnectors:output_type -> gibson.tenant.v1.ListConnectorsResponse
	9, // 9: gibson.tenant.v1.ConnectorService.DisableConnector:output_type -> gibson.tenant.v1.DisableConnectorResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gibson_tenant_v1_connector_proto_init() }
func file_gibson_tenant_v1_connector_proto_init() {
	if File_gibson_tenant_v1_connector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gibson_tenant_v1_connector_proto_rawDesc), len(file_gibson_tenant_v1_connector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gibson_tenant_v1_connector_proto_goTypes,
		DependencyIndexes: file_gibson_tenant_v1_connector_proto_depIdxs,
		MessageInfos:      file_gibson_tenant_v1_connector_proto_msgTypes,
	}.Build()
	File_gibson_tenant_v1_connector_proto = out.File
	file_gibson_tenant_v1_connector_proto_goTypes = nil
	file_gibson_tenant_v1_connector_proto_depIdxs = nil
}
